name: barcode_scanner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  mobile_scanner: ^3.5.6
  convert: ^3.1.1
  http: ^1.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  # mobile_scanner: ^5.0.1
  google_fonts:
  percent_indicator:
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker: ^1.1.1
  flutter_native_splash: ^2.4.0
  camera: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
# flutter_icons:
  ios: true       # iOSのアイコンを生成し、デフォルトのものと置き換えるか
  # android: true   # Androidのアイコンを生成し、デフォルトのものと置き換えるか
  android: launcher_icon   # Androidのアイコンを生成し、デフォルトのものと置き換えるか
  image_path: "assets/images/application.png"   # アイコン画像のパス
  adaptive_icon_foreground: "assets/images/adaptive_icon_foreground.png"
  adaptive_icon_background: "assets/images/adaptive_icon_background.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/google_fonts/

flutter_native_splash:
  color: "#00FFFF"  # スプラッシュ画面の背景色
  image: "assets/images/splash.png" # スプラッシュ画面の中央に表示する画像

  android_12:   # 12以上の標準スプラッシュ画面の設定
    color: "#FF00FF"
    image: "assets/images/splash.png"
  
  # android_gravity: left   # Androidアイコンの画像の位置
  # ios_content_mode: left  # iOSのアイコンの画像の位置
